# Generated by Django 5.2.11 on 2026-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complated', 'Complated'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
